insert into business (name_business, address_id_address) values ('Venison - Racks Frenched', 11);
insert into business (name_business, address_id_address) values ('Poppy Seed', 12);
insert into business (name_business, address_id_address) values ('Cheese - Victor Et Berthold', 13);
insert into business (name_business, address_id_address) values ('Cookies Almond Hazelnut', 14);
insert into business (name_business, address_id_address) values ('Tart Shells - Savory, 4', 15);
insert into business (name_business, address_id_address) values ('Sausage - Liver', 16);
insert into business (name_business, address_id_address) values ('Cabbage - Nappa', 17);
insert into business (name_business, address_id_address) values ('Container - Foam Dixie 12 Oz', 18);
insert into business (name_business, address_id_address) values ('Yogurt - French Vanilla', 19);
insert into business (name_business, address_id_address) values ('Muffin Batt - Carrot Spice', 20);
insert into business (name_business, address_id_address) values ('Sour Puss Sour Apple', 21);
insert into business (name_business, address_id_address) values ('Chicken - Ground', 22);
insert into business (name_business, address_id_address) values ('Oregano - Fresh', 23);
insert into business (name_business, address_id_address) values ('Lid - Translucent, 3.5 And 6 Oz', 24);
insert into business (name_business, address_id_address) values ('Asparagus - Mexican', 25);
insert into business (name_business, address_id_address) values ('Tray - Foam, Square 4 - S', 26);
insert into business (name_business, address_id_address) values ('Banana - Green', 27);
insert into business (name_business, address_id_address) values ('Lemons', 28);
insert into business (name_business, address_id_address) values ('Pork - Hock And Feet Attached', 29);
insert into business (name_business, address_id_address) values ('Chivas Regal - 12 Year Old', 30);
insert into business (name_business, address_id_address) values ('Pork Casing', 31);
insert into business (name_business, address_id_address) values ('Beef Flat Iron Steak', 32);
insert into business (name_business, address_id_address) values ('Sauce - Soya, Light', 33);
insert into business (name_business, address_id_address) values ('Cookie - Oatmeal', 34);
insert into business (name_business, address_id_address) values ('Star Fruit', 35);
insert into business (name_business, address_id_address) values ('Tomatoes - Cherry, Yellow', 36);
insert into business (name_business, address_id_address) values ('Brandy - Bar', 37);
insert into business (name_business, address_id_address) values ('Ice Cream - Life Savers', 38);
insert into business (name_business, address_id_address) values ('Sprouts - Peppercress', 39);
insert into business (name_business, address_id_address) values ('Coffee Swiss Choc Almond', 40);
insert into business (name_business, address_id_address) values ('Cake - Pancake', 41);
insert into business (name_business, address_id_address) values ('Hog / Sausage Casing - Pork', 42);
insert into business (name_business, address_id_address) values ('Sprite, Diet - 355ml', 43);
insert into business (name_business, address_id_address) values ('Napkin White - Starched', 44);
insert into business (name_business, address_id_address) values ('Lychee', 45);
insert into business (name_business, address_id_address) values ('Lettuce - Escarole', 46);
insert into business (name_business, address_id_address) values ('Mayonnaise - Individual Pkg', 47);
insert into business (name_business, address_id_address) values ('Salmon - Whole, 4 - 6 Pounds', 48);
insert into business (name_business, address_id_address) values ('Hummus - Spread', 49);
insert into business (name_business, address_id_address) values ('Flour - Strong Pizza', 50);
insert into business (name_business, address_id_address) values ('Pastry - Apple Muffins - Mini', 51);
insert into business (name_business, address_id_address) values ('Ice Cream Bar - Hageen Daz To', 52);
insert into business (name_business, address_id_address) values ('Soup - French Can Pea', 53);
insert into business (name_business, address_id_address) values ('Cheese - Goat With Herbs', 54);
insert into business (name_business, address_id_address) values ('Oil - Sesame', 55);
insert into business (name_business, address_id_address) values ('Capicola - Hot', 56);
insert into business (name_business, address_id_address) values ('Sauce - Hollandaise', 57);
insert into business (name_business, address_id_address) values ('Chocolate - Semi Sweet', 58);
insert into business (name_business, address_id_address) values ('Pastry - Cherry Danish - Mini', 59);
insert into business (name_business, address_id_address) values ('Foie Gras', 60);
insert into business (name_business, address_id_address) values ('Puree - Strawberry', 61);
insert into business (name_business, address_id_address) values ('Milk - 1%', 62);
insert into business (name_business, address_id_address) values ('Longos - Grilled Salmon With Bbq', 63);
insert into business (name_business, address_id_address) values ('Muffin - Mix - Strawberry Rhubarb', 64);
insert into business (name_business, address_id_address) values ('Lid - Translucent, 3.5 And 6 Oz', 65);
insert into business (name_business, address_id_address) values ('Table Cloth 81x81 White', 66);
insert into business (name_business, address_id_address) values ('Buffalo - Striploin', 67);
insert into business (name_business, address_id_address) values ('Lentils - Green Le Puy', 68);
insert into business (name_business, address_id_address) values ('Tart Shells - Savory, 4', 69);
insert into business (name_business, address_id_address) values ('Greens Mustard', 70);
insert into business (name_business, address_id_address) values ('Juice - V8 Splash', 71);
insert into business (name_business, address_id_address) values ('Pork - Belly Fresh', 72);
insert into business (name_business, address_id_address) values ('Truffle Cups - Red', 73);
insert into business (name_business, address_id_address) values ('Veal - Inside, Choice', 74);
insert into business (name_business, address_id_address) values ('Tea Leaves - Oolong', 75);
insert into business (name_business, address_id_address) values ('Figs', 76);
insert into business (name_business, address_id_address) values ('Coriander - Seed', 77);
insert into business (name_business, address_id_address) values ('Cheese - Stilton', 78);
insert into business (name_business, address_id_address) values ('Oil - Shortening - All - Purpose', 79);
insert into business (name_business, address_id_address) values ('Bread - Petit Baguette', 80);
insert into business (name_business, address_id_address) values ('Tabasco Sauce, 2 Oz', 81);
insert into business (name_business, address_id_address) values ('Split Peas - Green, Dry', 82);
insert into business (name_business, address_id_address) values ('Cocoa Butter', 83);
insert into business (name_business, address_id_address) values ('Port - 74 Brights', 84);
insert into business (name_business, address_id_address) values ('Tomatoes - Vine Ripe, Red', 85);
insert into business (name_business, address_id_address) values ('Pasta - Rotini, Colour, Dry', 86);
insert into business (name_business, address_id_address) values ('Wine - Sawmill Creek Autumn', 87);
insert into business (name_business, address_id_address) values ('Chocolate - Liqueur Cups With Foil', 88);
insert into business (name_business, address_id_address) values ('Yoghurt Tubes', 89);
insert into business (name_business, address_id_address) values ('Bagel - Whole White Sesame', 90);
insert into business (name_business, address_id_address) values ('Tuna - Canned, Flaked, Light', 91);
insert into business (name_business, address_id_address) values ('Wine - Chianti Classico Riserva', 92);
insert into business (name_business, address_id_address) values ('Cheese - Cottage Cheese', 93);
insert into business (name_business, address_id_address) values ('Spic And Span All Purpose', 94);
insert into business (name_business, address_id_address) values ('Cookie Dough - Peanut Butter', 95);
insert into business (name_business, address_id_address) values ('Wine - Port Late Bottled Vintage', 96);
insert into business (name_business, address_id_address) values ('Syrup - Pancake', 97);
insert into business (name_business, address_id_address) values ('Cakes Assorted', 98);
insert into business (name_business, address_id_address) values ('Tea - Jasmin Green', 99);
insert into business (name_business, address_id_address) values ('Bread - Pain Au Liat X12', 100);
insert into business (name_business, address_id_address) values ('Fuji Apples', 101);
insert into business (name_business, address_id_address) values ('Rice Paper', 102);
insert into business (name_business, address_id_address) values ('Pork - Sausage, Medium', 103);
insert into business (name_business, address_id_address) values ('Mushrooms - Honey', 104);
insert into business (name_business, address_id_address) values ('Pears - Fiorelle', 105);
insert into business (name_business, address_id_address) values ('Cheese - Perron Cheddar', 106);
insert into business (name_business, address_id_address) values ('Olives - Morracan Dired', 107);
insert into business (name_business, address_id_address) values ('Wine - Winzer Krems Gruner', 108);
insert into business (name_business, address_id_address) values ('Spinach - Spinach Leaf', 109);
insert into business (name_business, address_id_address) values ('Wine - Sawmill Creek Autumn', 110);
insert into business (name_business, address_id_address) values ('Bread - Bagels, Plain', 111);
insert into business (name_business, address_id_address) values ('Lemonade - Mandarin, 591 Ml', 112);
insert into business (name_business, address_id_address) values ('Raspberries - Frozen', 113);
insert into business (name_business, address_id_address) values ('Milk 2% 500 Ml', 114);
insert into business (name_business, address_id_address) values ('Fondant - Icing', 115);
insert into business (name_business, address_id_address) values ('Sansho Powder', 116);
insert into business (name_business, address_id_address) values ('Beer - True North Lager', 117);
insert into business (name_business, address_id_address) values ('Juice - Pineapple, 341 Ml', 118);
insert into business (name_business, address_id_address) values ('Muffin Mix - Raisin Bran', 119);
insert into business (name_business, address_id_address) values ('Chickhen - Chicken Phyllo', 120);
insert into business (name_business, address_id_address) values ('Asparagus - White, Fresh', 121);
insert into business (name_business, address_id_address) values ('Cookie Dough - Peanut Butter', 122);
insert into business (name_business, address_id_address) values ('Apple - Fuji', 123);
insert into business (name_business, address_id_address) values ('Milk - 1%', 124);
insert into business (name_business, address_id_address) values ('Crush - Orange, 355ml', 125);
insert into business (name_business, address_id_address) values ('Puree - Pear', 126);
insert into business (name_business, address_id_address) values ('Wine - White, Riesling, Henry Of', 127);
insert into business (name_business, address_id_address) values ('Sloe Gin - Mcguinness', 128);
insert into business (name_business, address_id_address) values ('Glaze - Apricot', 129);
insert into business (name_business, address_id_address) values ('Instant Coffee', 130);
insert into business (name_business, address_id_address) values ('Longos - Greek Salad', 131);
insert into business (name_business, address_id_address) values ('Whmis - Spray Bottle Trigger', 132);
insert into business (name_business, address_id_address) values ('Beef Wellington', 133);
insert into business (name_business, address_id_address) values ('Vaccum Bag 10x13', 134);
insert into business (name_business, address_id_address) values ('Doilies - 8, Paper', 135);
insert into business (name_business, address_id_address) values ('Neckerchief Blck', 136);
insert into business (name_business, address_id_address) values ('Garam Marsala', 137);
insert into business (name_business, address_id_address) values ('Crab - Blue, Frozen', 138);
insert into business (name_business, address_id_address) values ('Lettuce - Boston Bib', 139);
insert into business (name_business, address_id_address) values ('Wine - Red, Black Opal Shiraz', 140);
insert into business (name_business, address_id_address) values ('Fenngreek Seed', 141);
insert into business (name_business, address_id_address) values ('Cheese - Perron Cheddar', 142);
insert into business (name_business, address_id_address) values ('Wine - Clavet Saint Emilion', 143);
insert into business (name_business, address_id_address) values ('Bread - Raisin Walnut Pull', 144);
insert into business (name_business, address_id_address) values ('Red Cod Fillets - 225g', 145);
insert into business (name_business, address_id_address) values ('Extract - Lemon', 146);
insert into business (name_business, address_id_address) values ('Pur Value', 147);
insert into business (name_business, address_id_address) values ('Mayonnaise - Individual Pkg', 148);
insert into business (name_business, address_id_address) values ('Crab - Dungeness, Whole', 149);
insert into business (name_business, address_id_address) values ('Sugar - Palm', 150);
insert into business (name_business, address_id_address) values ('Chocolate - Unsweetened', 151);
insert into business (name_business, address_id_address) values ('Berry Brulee', 152);
insert into business (name_business, address_id_address) values ('Cactus Pads', 153);
insert into business (name_business, address_id_address) values ('Cheese - Brie Roitelet', 154);
insert into business (name_business, address_id_address) values ('Lettuce - Boston Bib - Organic', 155);
insert into business (name_business, address_id_address) values ('Table Cloth 62x114 Colour', 156);
insert into business (name_business, address_id_address) values ('Sea Bass - Fillets', 157);
insert into business (name_business, address_id_address) values ('Dried Figs', 158);
insert into business (name_business, address_id_address) values ('Spring Roll Wrappers', 159);
insert into business (name_business, address_id_address) values ('Plasticspoonblack', 160);
insert into business (name_business, address_id_address) values ('Table Cloth 120 Round White', 161);
insert into business (name_business, address_id_address) values ('Baking Powder', 162);
insert into business (name_business, address_id_address) values ('Chips - Doritos', 163);
insert into business (name_business, address_id_address) values ('Table Cloth 90x90 White', 164);
insert into business (name_business, address_id_address) values ('Pork - Bacon, Double Smoked', 165);
insert into business (name_business, address_id_address) values ('Onion - Dried', 166);
insert into business (name_business, address_id_address) values ('Pants Custom Dry Clean', 167);
insert into business (name_business, address_id_address) values ('Corn - Mini', 168);
insert into business (name_business, address_id_address) values ('Pork - Chop, Frenched', 169);
insert into business (name_business, address_id_address) values ('Wine - Coteaux Du Tricastin Ac', 170);
insert into business (name_business, address_id_address) values ('Pepper - Julienne, Frozen', 171);
insert into business (name_business, address_id_address) values ('Pastry - Plain Baked Croissant', 172);
insert into business (name_business, address_id_address) values ('Lambcasing', 173);
insert into business (name_business, address_id_address) values ('Beer - Corona', 174);
insert into business (name_business, address_id_address) values ('Pea - Snow', 175);
insert into business (name_business, address_id_address) values ('Longos - Cheese Tortellini', 176);
insert into business (name_business, address_id_address) values ('Vaccum Bag - 14x20', 177);
insert into business (name_business, address_id_address) values ('Juice - Orange, Concentrate', 178);
insert into business (name_business, address_id_address) values ('Soup - Base Broth Beef', 179);
insert into business (name_business, address_id_address) values ('Garlic Powder', 180);
insert into business (name_business, address_id_address) values ('Shrimp - Black Tiger 8 - 12', 181);
insert into business (name_business, address_id_address) values ('Nut - Peanut, Roasted', 182);
insert into business (name_business, address_id_address) values ('Wine - Pinot Noir Mondavi Coastal', 183);
insert into business (name_business, address_id_address) values ('Cod - Black Whole Fillet', 184);
insert into business (name_business, address_id_address) values ('Wine - Dubouef Macon - Villages', 185);
insert into business (name_business, address_id_address) values ('Sage - Rubbed', 186);
insert into business (name_business, address_id_address) values ('Carbonated Water - Wildberry', 187);
insert into business (name_business, address_id_address) values ('Soup - Campbells Beef Noodle', 188);
insert into business (name_business, address_id_address) values ('Pork - Suckling Pig', 189);
insert into business (name_business, address_id_address) values ('Lobster - Canned Premium', 190);
insert into business (name_business, address_id_address) values ('Beets - Candy Cane, Organic', 191);
insert into business (name_business, address_id_address) values ('Liqueur Banana, Ramazzotti', 192);
insert into business (name_business, address_id_address) values ('Beer - Muskoka Cream Ale', 193);
insert into business (name_business, address_id_address) values ('Sambuca Cream', 194);
insert into business (name_business, address_id_address) values ('Puree - Strawberry', 195);
insert into business (name_business, address_id_address) values ('Instant Coffee', 196);
insert into business (name_business, address_id_address) values ('Roe - Lump Fish, Black', 197);
insert into business (name_business, address_id_address) values ('Cake - Mini Potato Pancake', 198);
insert into business (name_business, address_id_address) values ('Grapefruit - White', 199);
insert into business (name_business, address_id_address) values ('Wine - Taylors Reserve', 200);
insert into business (name_business, address_id_address) values ('Sprouts - Corn', 201);
insert into business (name_business, address_id_address) values ('Sauce Bbq Smokey', 202);
insert into business (name_business, address_id_address) values ('Juice - Clamato, 341 Ml', 203);
insert into business (name_business, address_id_address) values ('Oil - Food, Lacquer Spray', 204);
insert into business (name_business, address_id_address) values ('Yoplait - Strawbrasp Peac', 205);
insert into business (name_business, address_id_address) values ('Cheese - Goat With Herbs', 206);
insert into business (name_business, address_id_address) values ('Crab - Blue, Frozen', 207);
insert into business (name_business, address_id_address) values ('Grapes - Red', 208);
insert into business (name_business, address_id_address) values ('Cheese - Stilton', 209);
insert into business (name_business, address_id_address) values ('Potatoes - Instant, Mashed', 210);
