insert into dish (name, description, cost, business_id_business) values ('Cabbage - Red', 'Cheese - Goat With Herbs', 34.18, 66);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Fontina', 'Chicken - Tenderloin', 9.5, 164);
insert into dish (name, description, cost, business_id_business) values ('Fruit Salad Deluxe', 'Yeast Dry - Fleischman', 90.8, 198);
insert into dish (name, description, cost, business_id_business) values ('Flour - Bran, Red', 'Corn - On The Cob', 48.46, 66);
insert into dish (name, description, cost, business_id_business) values ('Bar Mix - Lime', 'Muffin Mix - Oatmeal', 9.99, 150);
insert into dish (name, description, cost, business_id_business) values ('Soupcontfoam16oz 116con', 'Spice - Pepper Portions', 92.35, 81);
insert into dish (name, description, cost, business_id_business) values ('Carbonated Water - Lemon Lime', 'Bread - Granary Small Pull', 99.6, 156);
insert into dish (name, description, cost, business_id_business) values ('Muffin Batt - Choc Chk', 'Cheese - Perron Cheddar', 35.62, 162);
insert into dish (name, description, cost, business_id_business) values ('Wine - Casillero Del Diablo', 'Pepper - Green Thai', 20.92, 188);
insert into dish (name, description, cost, business_id_business) values ('Hand Towel', 'Oil - Safflower', 14.11, 135);
insert into dish (name, description, cost, business_id_business) values ('Sobe - Green Tea', 'Gooseberry', 13.97, 97);
insert into dish (name, description, cost, business_id_business) values ('Pork - Belly Fresh', 'Beef Ground Medium', 16.04, 71);
insert into dish (name, description, cost, business_id_business) values ('Milkettes - 2%', 'Onions - White', 87.75, 127);
insert into dish (name, description, cost, business_id_business) values ('Chef Hat 25cm', 'Placemat - Scallop, White', 91.5, 46);
insert into dish (name, description, cost, business_id_business) values ('Beef - Top Sirloin', 'Wine - Sauvignon Blanc', 25.45, 82);
insert into dish (name, description, cost, business_id_business) values ('Cranberries - Frozen', 'Sauce - Demi Glace', 82.68, 74);
insert into dish (name, description, cost, business_id_business) values ('Sprouts - Bean', 'Wine - Beaujolais Villages', 11.53, 117);
insert into dish (name, description, cost, business_id_business) values ('Oil - Peanut', 'Shrimp - Baby, Warm Water', 45.61, 131);
insert into dish (name, description, cost, business_id_business) values ('Milk - Skim', 'Rye Special Old', 82.87, 188);
insert into dish (name, description, cost, business_id_business) values ('Ecolab - Power Fusion', 'Cheese - Sheep Milk', 90.65, 67);
insert into dish (name, description, cost, business_id_business) values ('Pate - Cognac', 'Pork Loin Cutlets', 55.54, 132);
insert into dish (name, description, cost, business_id_business) values ('Wine - Red Oakridge Merlot', 'Oven Mitts 17 Inch', 45.75, 108);
insert into dish (name, description, cost, business_id_business) values ('Sugar - Invert', 'Bread Fig And Almond', 80.17, 159);
insert into dish (name, description, cost, business_id_business) values ('Pie Box - Cello Window 2.5', 'Muffin - Mix - Creme Brule 15l', 22.31, 103);
insert into dish (name, description, cost, business_id_business) values ('Wine - Red, Marechal Foch', 'Otomegusa Dashi Konbu', 7.0, 131);
insert into dish (name, description, cost, business_id_business) values ('Basil - Dry, Rubbed', 'Bread - Bagels, Mini', 62.67, 81);
insert into dish (name, description, cost, business_id_business) values ('Snapple - Iced Tea Peach', 'Wine - White, French Cross', 8.25, 70);
insert into dish (name, description, cost, business_id_business) values ('Clams - Canned', 'Cheese - Brie Roitelet', 58.7, 35);
insert into dish (name, description, cost, business_id_business) values ('Thyme - Fresh', 'Wine - Taylors Reserve', 9.4, 99);
insert into dish (name, description, cost, business_id_business) values ('Napkin - Cocktail,beige 2 - Ply', 'Bar Mix - Pina Colada, 355 Ml', 94.82, 79);
insert into dish (name, description, cost, business_id_business) values ('Jameson - Irish Whiskey', 'Shrimp - Tiger 21/25', 44.0, 118);
insert into dish (name, description, cost, business_id_business) values ('Soup - Clam Chowder, Dry Mix', 'Coffee - 10oz Cup 92961', 65.18, 167);
insert into dish (name, description, cost, business_id_business) values ('Sauerkraut', 'Plate - Foam, Bread And Butter', 24.15, 42);
insert into dish (name, description, cost, business_id_business) values ('Beer - Camerons Auburn', 'Tomatoes', 69.36, 111);
insert into dish (name, description, cost, business_id_business) values ('Gatorade - Lemon Lime', 'Sauce Bbq Smokey', 92.51, 197);
insert into dish (name, description, cost, business_id_business) values ('Soap - Hand Soap', 'Sprouts - Pea', 52.69, 179);
insert into dish (name, description, cost, business_id_business) values ('Caviar - Salmon', 'Cheese - Taleggio D.o.p.', 45.49, 176);
insert into dish (name, description, cost, business_id_business) values ('Wine - White, Concha Y Toro', 'Appetizer - Shrimp Puff', 66.54, 193);
insert into dish (name, description, cost, business_id_business) values ('Wine - Beaujolais Villages', 'Pork - Tenderloin, Frozen', 56.24, 78);
insert into dish (name, description, cost, business_id_business) values ('Sugar - Cubes', 'Kahlua', 47.42, 176);
insert into dish (name, description, cost, business_id_business) values ('Pastry - Chocolate Marble Tea', 'Pasta - Rotini, Colour, Dry', 31.99, 58);
insert into dish (name, description, cost, business_id_business) values ('Cookie - Oreo 100x2', 'Beef - Ground Medium', 89.24, 185);
insert into dish (name, description, cost, business_id_business) values ('Magnotta - Bel Paese White', 'Milk - Homo', 54.75, 84);
insert into dish (name, description, cost, business_id_business) values ('Tortillas - Flour, 8', 'Chocolate Bar - Coffee Crisp', 98.28, 142);
insert into dish (name, description, cost, business_id_business) values ('Pate - Cognac', 'Bread Crumbs - Japanese Style', 9.01, 184);
insert into dish (name, description, cost, business_id_business) values ('Table Cloth 62x120 Colour', 'Cake - Cheese Cake 9 Inch', 22.54, 47);
insert into dish (name, description, cost, business_id_business) values ('Lemon Tarts', 'Cheese - Brick With Pepper', 29.06, 153);
insert into dish (name, description, cost, business_id_business) values ('V8 Splash Strawberry Kiwi', 'Butter - Salted', 5.59, 69);
insert into dish (name, description, cost, business_id_business) values ('Oregano - Fresh', 'Bread - Assorted Rolls', 59.66, 42);
insert into dish (name, description, cost, business_id_business) values ('Flour - Corn, Fine', 'Pate - Peppercorn', 28.53, 71);
insert into dish (name, description, cost, business_id_business) values ('Apple - Northern Spy', 'Chips Potato Salt Vinegar 43g', 51.71, 130);
insert into dish (name, description, cost, business_id_business) values ('Wine - Sauvignon Blanc', 'Pail - 4l White, With Handle', 41.51, 94);
insert into dish (name, description, cost, business_id_business) values ('Tarragon - Primerba, Paste', 'Wine - Chardonnay Mondavi', 43.58, 75);
insert into dish (name, description, cost, business_id_business) values ('Ice - Clear, 300 Lb For Carving', 'Wine - White, Colubia Cresh', 52.46, 96);
insert into dish (name, description, cost, business_id_business) values ('Butter Sweet', 'Melon - Honey Dew', 76.04, 166);
insert into dish (name, description, cost, business_id_business) values ('Ecolab - Lime - A - Way 4/4 L', 'Tart Shells - Savory, 2', 77.47, 21);
insert into dish (name, description, cost, business_id_business) values ('Truffle Cups - White Paper', '7up Diet, 355 Ml', 20.03, 35);
insert into dish (name, description, cost, business_id_business) values ('Doilies - 5, Paper', 'Pepper - Red Thai', 63.81, 58);
insert into dish (name, description, cost, business_id_business) values ('Container - Clear 32 Oz', 'Cod - Fillets', 48.31, 70);
insert into dish (name, description, cost, business_id_business) values ('Creme De Menthe Green', 'Fib N9 - Prague Powder', 77.16, 147);
insert into dish (name, description, cost, business_id_business) values ('Tarragon - Primerba, Paste', 'Eggplant Italian', 9.14, 48);
insert into dish (name, description, cost, business_id_business) values ('Marjoram - Dried, Rubbed', 'Apple - Royal Gala', 66.63, 32);
insert into dish (name, description, cost, business_id_business) values ('Garlic - Peeled', 'Beef - Cooked, Corned', 20.68, 62);
insert into dish (name, description, cost, business_id_business) values ('Bar Special K', 'Container Clear 8 Oz', 84.49, 199);
insert into dish (name, description, cost, business_id_business) values ('Tea - English Breakfast', 'Truffle Paste', 74.08, 128);
insert into dish (name, description, cost, business_id_business) values ('Fruit Salad Deluxe', 'Squeeze Bottle', 53.74, 151);
insert into dish (name, description, cost, business_id_business) values ('Sprouts - Alfalfa', 'Creamers - 10%', 7.28, 194);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Goat With Herbs', 'Coke - Classic, 355 Ml', 79.29, 66);
insert into dish (name, description, cost, business_id_business) values ('Langers - Ruby Red Grapfruit', 'Table Cloth 62x114 White', 83.37, 172);
insert into dish (name, description, cost, business_id_business) values ('Water - Mineral, Natural', 'Ecolab - Hand Soap Form Antibac', 79.83, 194);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Bocconcini', 'Cream Of Tartar', 78.23, 179);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Mix', 'Soup - Boston Clam Chowder', 73.96, 41);
insert into dish (name, description, cost, business_id_business) values ('Bread - Multigrain', 'Wheat - Soft Kernal Of Wheat', 71.93, 2);
insert into dish (name, description, cost, business_id_business) values ('Wine - White, Mosel Gold', 'Salad Dressing', 97.92, 31);
insert into dish (name, description, cost, business_id_business) values ('Oil - Olive Bertolli', 'Nectarines', 52.67, 10);
insert into dish (name, description, cost, business_id_business) values ('Wine - Jafflin Bourgongone', 'Placemat - Scallop, White', 15.32, 128);
insert into dish (name, description, cost, business_id_business) values ('Yukon Jack', 'Beef - Rib Roast, Cap On', 92.88, 67);
insert into dish (name, description, cost, business_id_business) values ('Heavy Duty Dust Pan', 'Kellogs Special K Cereal', 76.55, 56);
insert into dish (name, description, cost, business_id_business) values ('Corn Kernels - Frozen', 'Irish Cream - Baileys', 85.33, 76);
insert into dish (name, description, cost, business_id_business) values ('Broom Handle', 'Salt - Rock, Course', 22.9, 183);
insert into dish (name, description, cost, business_id_business) values ('Kolrabi', 'Pastry - Chocolate Marble Tea', 99.33, 171);
insert into dish (name, description, cost, business_id_business) values ('Bagels Poppyseed', 'Brandy Apricot', 42.46, 74);
insert into dish (name, description, cost, business_id_business) values ('Honey - Comb', 'Lamb - Shanks', 35.73, 106);
insert into dish (name, description, cost, business_id_business) values ('Mints - Striped Red', 'Sugar - Brown, Individual', 48.69, 105);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Orzo, Dry', 'Coffee - Espresso', 35.12, 20);
insert into dish (name, description, cost, business_id_business) values ('Coffee - Espresso', 'Pork - Loin, Boneless', 91.38, 140);
insert into dish (name, description, cost, business_id_business) values ('Pork - Tenderloin, Fresh', 'Split Peas - Green, Dry', 19.52, 145);
insert into dish (name, description, cost, business_id_business) values ('Iced Tea - Lemon, 460 Ml', 'Seabream Whole Farmed', 6.07, 25);
insert into dish (name, description, cost, business_id_business) values ('Chutney Sauce', 'Grand Marnier', 96.04, 198);
insert into dish (name, description, cost, business_id_business) values ('Dill Weed - Dry', 'Chicken - Leg, Boneless', 60.53, 39);
insert into dish (name, description, cost, business_id_business) values ('Squash - Pattypan, Yellow', 'Coffee - Espresso', 60.17, 56);
insert into dish (name, description, cost, business_id_business) values ('Wine - Shiraz Wolf Blass Premium', 'Tea Leaves - Oolong', 83.47, 10);
insert into dish (name, description, cost, business_id_business) values ('Appetiser - Bought', 'Shopper Bag - S - 4', 97.93, 122);
insert into dish (name, description, cost, business_id_business) values ('Wine - German Riesling', 'Cocoa Butter', 79.86, 6);
insert into dish (name, description, cost, business_id_business) values ('Bread - Wheat Baguette', 'Ice Cream Bar - Drumstick', 16.1, 48);
insert into dish (name, description, cost, business_id_business) values ('Cinnamon Buns Sticky', 'Wiberg Super Cure', 21.55, 31);
insert into dish (name, description, cost, business_id_business) values ('Juice - Clam, 46 Oz', 'Pork - Hock And Feet Attached', 50.58, 43);
insert into dish (name, description, cost, business_id_business) values ('Tart - Lemon', 'Chips - Potato Jalapeno', 88.53, 200);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Bakers Cream Cheese', 'Juice - Grape, White', 28.54, 54);
insert into dish (name, description, cost, business_id_business) values ('Pea - Snow', 'Irish Cream - Butterscotch', 87.04, 125);
insert into dish (name, description, cost, business_id_business) values ('Honey - Liquid', 'Beer - Mcauslan Apricot', 18.15, 117);
insert into dish (name, description, cost, business_id_business) values ('Bread - English Muffin', 'Chicken - Thigh, Bone In', 32.51, 130);
insert into dish (name, description, cost, business_id_business) values ('Energy Drink - Franks Original', 'Tuna - Canned, Flaked, Light', 86.89, 194);
insert into dish (name, description, cost, business_id_business) values ('Ezy Change Mophandle', 'Sesame Seed', 23.91, 49);
insert into dish (name, description, cost, business_id_business) values ('Onions - Pearl', 'Ice - Clear, 300 Lb For Carving', 98.17, 68);
insert into dish (name, description, cost, business_id_business) values ('Mountain Dew', 'Pork - Ground', 21.36, 185);
insert into dish (name, description, cost, business_id_business) values ('Lamb Rack - Ontario', 'Ice Cream Bar - Rolo Cone', 87.31, 52);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chablis J Moreau Et Fils', 'Fib N9 - Prague Powder', 95.58, 138);
insert into dish (name, description, cost, business_id_business) values ('Wood Chips - Regular', 'Turkey Tenderloin Frozen', 75.31, 187);
insert into dish (name, description, cost, business_id_business) values ('Crush - Orange, 355ml', 'Table Cloth 90x90 White', 52.14, 125);
insert into dish (name, description, cost, business_id_business) values ('Cheese - La Sauvagine', 'Cake - Dulce De Leche', 65.66, 37);
insert into dish (name, description, cost, business_id_business) values ('Broom - Push', 'Wine - White, Riesling, Semi - Dry', 52.05, 26);
insert into dish (name, description, cost, business_id_business) values ('Carrots - Purple, Organic', 'Curry Paste - Madras', 10.07, 173);
insert into dish (name, description, cost, business_id_business) values ('Tuna - Loin', 'Vinegar - Champagne', 26.52, 16);
insert into dish (name, description, cost, business_id_business) values ('Russian Prince', 'Ecolab - Orange Frc, Cleaner', 74.12, 127);
insert into dish (name, description, cost, business_id_business) values ('Beef Dry Aged Tenderloin Aaa', 'Cheese - Grie Des Champ', 38.21, 161);
insert into dish (name, description, cost, business_id_business) values ('Almonds Ground Blanched', 'Wine - Jackson Triggs Okonagan', 72.63, 49);
insert into dish (name, description, cost, business_id_business) values ('Squeeze Bottle', 'Tahini Paste', 58.33, 41);
insert into dish (name, description, cost, business_id_business) values ('Table Cloth 62x114 White', 'Pork - European Side Bacon', 82.65, 160);
insert into dish (name, description, cost, business_id_business) values ('Bread - Olive Dinner Roll', 'Cinnamon Buns Sticky', 46.45, 188);
insert into dish (name, description, cost, business_id_business) values ('Peas - Frozen', 'Pepper - Yellow Bell', 17.03, 184);
insert into dish (name, description, cost, business_id_business) values ('Nut - Walnut, Pieces', 'Pork Loin Bine - In Frenched', 84.0, 23);
insert into dish (name, description, cost, business_id_business) values ('Tomato - Tricolor Cherry', 'Bagel - Whole White Sesame', 54.36, 181);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells Chili Veg', 'Fish - Bones', 33.44, 199);
insert into dish (name, description, cost, business_id_business) values ('Cattail Hearts', 'Tuna - Fresh', 16.31, 160);
insert into dish (name, description, cost, business_id_business) values ('Jolt Cola - Electric Blue', 'Paste - Black Olive', 65.29, 7);
insert into dish (name, description, cost, business_id_business) values ('Piping Jelly - All Colours', 'Tomatoes Tear Drop Yellow', 91.74, 24);
insert into dish (name, description, cost, business_id_business) values ('Clams - Canned', 'Milk - Chocolate 250 Ml', 60.84, 17);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Romaine, Heart', 'Bread - Onion Focaccia', 65.34, 104);
insert into dish (name, description, cost, business_id_business) values ('Oranges - Navel, 72', 'The Pop Shoppe - Lime Rickey', 95.97, 109);
insert into dish (name, description, cost, business_id_business) values ('Fireball Whisky', 'Chicken Giblets', 64.13, 128);
insert into dish (name, description, cost, business_id_business) values ('Dish Towel', 'Flavouring Vanilla Artificial', 43.75, 128);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Comtomme', 'White Baguette', 94.8, 82);
insert into dish (name, description, cost, business_id_business) values ('Foam Dinner Plate', 'Tea - Grapefruit Green Tea', 40.11, 132);
insert into dish (name, description, cost, business_id_business) values ('Wild Boar - Tenderloin', 'Potatoes - Idaho 100 Count', 26.05, 123);
insert into dish (name, description, cost, business_id_business) values ('Dc - Frozen Momji', 'Sugar - Splenda Sweetener', 59.97, 37);
insert into dish (name, description, cost, business_id_business) values ('Lobster - Base', 'Cake - Box Window 10x10x2.5', 52.87, 65);
insert into dish (name, description, cost, business_id_business) values ('Plasticforkblack', 'Edible Flower - Mixed', 53.3, 66);
insert into dish (name, description, cost, business_id_business) values ('Napkin - Dinner, White', 'Nectarines', 5.4, 52);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells Tomato Ravioli', 'Bread - Rye', 54.58, 43);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Spaghetti, Dry', 'Spice - Greek 1 Step', 54.06, 101);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Fontina', 'Tea - Herbal Sweet Dreams', 87.04, 135);
insert into dish (name, description, cost, business_id_business) values ('Soup - Knorr, Classic Can. Chili', 'Peas - Pigeon, Dry', 58.07, 45);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells', 'Squid - Breaded', 25.73, 14);
insert into dish (name, description, cost, business_id_business) values ('Creme De Cacao Mcguines', 'Mayonnaise', 62.42, 142);
insert into dish (name, description, cost, business_id_business) values ('Mushroom - Crimini', 'Goulash Seasoning', 76.04, 19);
insert into dish (name, description, cost, business_id_business) values ('Pastry - French Mini Assorted', 'Cheese - Mix', 68.72, 13);
insert into dish (name, description, cost, business_id_business) values ('Cherries - Bing, Canned', 'Beets', 58.1, 195);
insert into dish (name, description, cost, business_id_business) values ('Alize Gold Passion', 'Ecolab - Balanced Fusion', 56.33, 4);
insert into dish (name, description, cost, business_id_business) values ('Bagel - Everything Presliced', 'Cheese - Boursin, Garlic / Herbs', 78.75, 3);
insert into dish (name, description, cost, business_id_business) values ('Tortillas - Flour, 10', 'Cake - Pancake', 22.69, 191);
insert into dish (name, description, cost, business_id_business) values ('Cup - 6oz, Foam', 'Breakfast Quesadillas', 58.04, 8);
insert into dish (name, description, cost, business_id_business) values ('Food Colouring - Green', 'Laundry - Bag Cloth', 10.68, 99);
insert into dish (name, description, cost, business_id_business) values ('Lobster - Baby, Boiled', 'Cake Sheet Combo Party Pack', 96.54, 41);
insert into dish (name, description, cost, business_id_business) values ('Mushroom - Enoki, Fresh', 'Wine - Magnotta, Merlot Sr Vqa', 67.98, 106);
insert into dish (name, description, cost, business_id_business) values ('Broom - Push', 'Sauce - Hollandaise', 57.23, 8);
insert into dish (name, description, cost, business_id_business) values ('Tea - Vanilla Chai', 'Chervil - Fresh', 40.79, 173);
insert into dish (name, description, cost, business_id_business) values ('Water - Perrier', 'Capicola - Hot', 29.39, 27);
insert into dish (name, description, cost, business_id_business) values ('Island Oasis - Pina Colada', 'Muffin - Mix - Strawberry Rhubarb', 77.5, 113);
insert into dish (name, description, cost, business_id_business) values ('Onions - Cooking', 'Tea - Honey Green Tea', 28.6, 195);
insert into dish (name, description, cost, business_id_business) values ('Crab - Dungeness, Whole, live', 'Wine - Blue Nun Qualitatswein', 81.96, 129);
insert into dish (name, description, cost, business_id_business) values ('V8 Splash Strawberry Banana', 'Veal - Inside Round / Top, Lean', 60.12, 136);
insert into dish (name, description, cost, business_id_business) values ('Bread - Italian Sesame Poly', 'Devonshire Cream', 71.32, 155);
insert into dish (name, description, cost, business_id_business) values ('Lamb - Whole Head Off,nz', 'Bread Country Roll', 8.7, 70);
insert into dish (name, description, cost, business_id_business) values ('Bar Mix - Lime', 'Sorrel - Fresh', 99.19, 131);
insert into dish (name, description, cost, business_id_business) values ('Beef - Tongue, Cooked', 'Pork - Hock And Feet Attached', 95.16, 166);
insert into dish (name, description, cost, business_id_business) values ('Beer - Corona', 'Yogurt - Banana, 175 Gr', 39.35, 66);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Lolla Rosa', 'Cheese - Oka', 73.02, 148);
insert into dish (name, description, cost, business_id_business) values ('Veal - Osso Bucco', 'Maintenance Removal Charge', 96.15, 70);
insert into dish (name, description, cost, business_id_business) values ('Pepper - Paprika, Spanish', 'Artichokes - Knobless, White', 61.13, 199);
insert into dish (name, description, cost, business_id_business) values ('Pork - European Side Bacon', 'Oil - Peanut', 13.93, 46);
insert into dish (name, description, cost, business_id_business) values ('Cake Circle, Paprus', 'Veal - Inside', 10.65, 64);
insert into dish (name, description, cost, business_id_business) values ('Vodka - Lemon, Absolut', 'Lettuce - Romaine, Heart', 85.2, 20);
insert into dish (name, description, cost, business_id_business) values ('Flour - So Mix Cake White', 'Soup - Chicken And Wild Rice', 22.84, 12);
insert into dish (name, description, cost, business_id_business) values ('Trout - Rainbow, Fresh', 'Gatorade - Fruit Punch', 90.54, 194);
insert into dish (name, description, cost, business_id_business) values ('Chocolate - Compound Coating', 'Water - Evian 355 Ml', 29.07, 199);
insert into dish (name, description, cost, business_id_business) values ('Puree - Blackcurrant', 'Table Cloth 53x69 White', 77.39, 28);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells Pasta Fagioli', 'Wine - Malbec Trapiche Reserve', 56.48, 41);
insert into dish (name, description, cost, business_id_business) values ('Oil - Coconut', 'Wine - Sherry Dry Sack, William', 36.51, 125);
insert into dish (name, description, cost, business_id_business) values ('Ecolab - Hand Soap Form Antibac', 'Amaretto', 20.13, 161);
insert into dish (name, description, cost, business_id_business) values ('Energy Drink - Franks Pineapple', 'Crab - Back Fin Meat, Canned', 97.92, 155);
insert into dish (name, description, cost, business_id_business) values ('Radish', 'Coffee - Decaffeinato Coffee', 17.55, 34);
insert into dish (name, description, cost, business_id_business) values ('Bread - Sour Sticks With Onion', 'Beer - Rickards Red', 31.35, 135);
insert into dish (name, description, cost, business_id_business) values ('Ham - Cooked Italian', 'Beer - Sleemans Honey Brown', 50.88, 198);
insert into dish (name, description, cost, business_id_business) values ('Turkey Tenderloin Frozen', 'Muffins - Assorted', 54.95, 77);
insert into dish (name, description, cost, business_id_business) values ('Star Anise, Whole', 'Hagen Daza - Dk Choocolate', 89.45, 73);
insert into dish (name, description, cost, business_id_business) values ('Pepper - Orange', 'Coffee - Decaffeinato Coffee', 50.86, 171);
insert into dish (name, description, cost, business_id_business) values ('Goat - Leg', 'Bagel - Ched Chs Presliced', 86.65, 102);
insert into dish (name, description, cost, business_id_business) values ('Cookie Dough - Peanut Butter', 'Veal - Slab Bacon', 29.66, 123);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Bakers Cream Cheese', 'Cod - Salted, Boneless', 59.84, 1);
insert into dish (name, description, cost, business_id_business) values ('Wine - Zinfandel California 2002', 'Bay Leaf Ground', 36.44, 165);
insert into dish (name, description, cost, business_id_business) values ('Asparagus - Frozen', 'Butter - Salted, Micro', 53.17, 25);
insert into dish (name, description, cost, business_id_business) values ('Cherries - Fresh', 'Bagel - Sesame Seed Presliced', 97.28, 56);
insert into dish (name, description, cost, business_id_business) values ('Wine - Rhine Riesling Wolf Blass', 'Juice - Cranberry, 341 Ml', 90.28, 199);
insert into dish (name, description, cost, business_id_business) values ('Wine - Soave Folonari', 'Phyllo Dough', 91.39, 106);
insert into dish (name, description, cost, business_id_business) values ('Plaintain', 'Puff Pastry - Sheets', 79.99, 35);
insert into dish (name, description, cost, business_id_business) values ('The Pop Shoppe - Cream Soda', 'Energy Drink - Franks Pineapple', 89.51, 143);
insert into dish (name, description, cost, business_id_business) values ('Bar Mix - Lemon', 'Croissant, Raw - Mini', 24.28, 164);
insert into dish (name, description, cost, business_id_business) values ('Milk - Homo', 'Squash - Sunburst', 16.76, 9);
insert into dish (name, description, cost, business_id_business) values ('Chocolate - Dark', 'Wine - Cahors Ac 2000, Clos', 32.95, 88);
insert into dish (name, description, cost, business_id_business) values ('Sauce - Cranberry', 'Knife Plastic - White', 25.34, 189);
insert into dish (name, description, cost, business_id_business) values ('Port - 74 Brights', 'Sour Puss - Tangerine', 27.04, 79);
insert into dish (name, description, cost, business_id_business) values ('Beer - Tetleys', 'Pepper Squash', 69.04, 104);
insert into dish (name, description, cost, business_id_business) values ('Sugar - Fine', 'Beans - Black Bean, Canned', 53.7, 1);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Escarole', 'Tomatoes Tear Drop', 42.25, 149);
insert into dish (name, description, cost, business_id_business) values ('Rum - Mount Gay Eclipes', 'Beef - Montreal Smoked Brisket', 5.77, 95);
insert into dish (name, description, cost, business_id_business) values ('Pork Ham Prager', 'Soup - Base Broth Beef', 49.29, 150);
insert into dish (name, description, cost, business_id_business) values ('Beer - Camerons Cream Ale', 'Beef - Flank Steak', 39.8, 172);
insert into dish (name, description, cost, business_id_business) values ('Lady Fingers', 'Bread - Corn Muffaleta Onion', 10.06, 144);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Cheddar, Mild', 'Garbage Bag - Clear', 44.76, 120);
insert into dish (name, description, cost, business_id_business) values ('Grapes - Black', 'Ecolab - Ster Bac', 75.76, 91);
insert into dish (name, description, cost, business_id_business) values ('Cake - Mini Potato Pancake', 'Chef Hat 25cm', 60.78, 136);
insert into dish (name, description, cost, business_id_business) values ('Carrots - Purple, Organic', 'Pork - Ham, Virginia', 63.19, 29);
insert into dish (name, description, cost, business_id_business) values ('Beets - Mini Golden', 'Ecolab - Hand Soap Form Antibac', 88.99, 78);
insert into dish (name, description, cost, business_id_business) values ('Clementine', 'Carroway Seed', 47.49, 196);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells, Lentil', 'Beef - Striploin Aa', 7.82, 121);
insert into dish (name, description, cost, business_id_business) values ('Cape Capensis - Fillet', 'Soup - Campbells Broccoli', 56.59, 50);
insert into dish (name, description, cost, business_id_business) values ('Mix Pina Colada', 'Tart Shells - Sweet, 3', 77.85, 87);
insert into dish (name, description, cost, business_id_business) values ('Bread - Dark Rye, Loaf', 'Chutney Sauce', 43.45, 102);
insert into dish (name, description, cost, business_id_business) values ('Cassis', 'Foam Tray S2', 69.2, 112);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chateau Timberlay', 'Cheese - Parmesan Grated', 35.67, 169);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Radicchio', 'Cheese - Manchego, Spanish', 26.59, 102);
insert into dish (name, description, cost, business_id_business) values ('Cookie - Oatmeal', 'Cookie Trail Mix', 89.01, 92);
insert into dish (name, description, cost, business_id_business) values ('Sea Bass - Fillets', 'Pants Custom Dry Clean', 98.04, 104);
insert into dish (name, description, cost, business_id_business) values ('Mousse - Banana Chocolate', 'Sprouts - Brussel', 36.9, 82);
insert into dish (name, description, cost, business_id_business) values ('Container - Hngd Cll Blk 7x7x3', 'Nantucket - 518ml', 9.19, 138);
insert into dish (name, description, cost, business_id_business) values ('Pork Loin Cutlets', 'Juice - Apple, 500 Ml', 39.2, 161);
insert into dish (name, description, cost, business_id_business) values ('Lamb - Racks, Frenched', 'Kiwi', 23.57, 64);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Victor Et Berthold', 'Beer - Maudite', 31.52, 14);
insert into dish (name, description, cost, business_id_business) values ('Apple - Granny Smith', 'Bread Country Roll', 34.98, 128);
insert into dish (name, description, cost, business_id_business) values ('Orange - Canned, Mandarin', 'Olives - Morracan Dired', 36.33, 99);
insert into dish (name, description, cost, business_id_business) values ('Chicken - Diced, Cooked', 'Carrots - Mini, Stem On', 12.84, 4);
insert into dish (name, description, cost, business_id_business) values ('Peas Snow', 'Longan', 7.67, 42);
insert into dish (name, description, cost, business_id_business) values ('Potatoes - Purple, Organic', 'Tabasco Sauce, 2 Oz', 69.02, 29);
insert into dish (name, description, cost, business_id_business) values ('Cotton Wet Mop 16 Oz', 'Potatoes - Yukon Gold, 80 Ct', 28.46, 171);
insert into dish (name, description, cost, business_id_business) values ('Wine - White, Gewurtzraminer', 'Halibut - Steaks', 39.66, 117);
insert into dish (name, description, cost, business_id_business) values ('Sobe - Green Tea', 'Rosemary - Primerba, Paste', 65.96, 177);
insert into dish (name, description, cost, business_id_business) values ('Radish', 'Piping Jelly - All Colours', 99.8, 78);
insert into dish (name, description, cost, business_id_business) values ('Muffin Carrot - Individual', 'Cookie Dough - Chocolate Chip', 51.4, 141);
insert into dish (name, description, cost, business_id_business) values ('Sauce - Hp', 'Skewers - Bamboo', 75.59, 45);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells, Minestrone', 'Rootbeer', 55.14, 17);
insert into dish (name, description, cost, business_id_business) values ('Bar Energy Chocchip', 'Gatorade - Xfactor Berry', 35.57, 129);
insert into dish (name, description, cost, business_id_business) values ('Devonshire Cream', 'Corn Meal', 96.69, 196);
insert into dish (name, description, cost, business_id_business) values ('Rice Paper', 'Ice Cream Bar - Oreo Sandwich', 60.31, 181);
insert into dish (name, description, cost, business_id_business) values ('Yukon Jack', 'Meldea Green Tea Liquor', 35.04, 169);
insert into dish (name, description, cost, business_id_business) values ('Pie Filling - Apple', 'Sauce - Chili', 75.99, 65);
insert into dish (name, description, cost, business_id_business) values ('Spinach - Spinach Leaf', 'Wine - Sherry Dry Sack, William', 41.9, 30);
insert into dish (name, description, cost, business_id_business) values ('Icecream - Dstk Strw Chseck', 'Wine - Magnotta, Merlot Sr Vqa', 73.94, 116);
insert into dish (name, description, cost, business_id_business) values ('Table Cloth 53x69 White', 'Muffin - Banana Nut Individual', 65.41, 76);
insert into dish (name, description, cost, business_id_business) values ('Cloves - Ground', 'Bananas', 39.92, 42);
insert into dish (name, description, cost, business_id_business) values ('Chocolate - Mi - Amere Semi', 'Sprouts - Baby Pea Tendrils', 90.51, 21);
insert into dish (name, description, cost, business_id_business) values ('Petit Baguette', 'V8 - Tropical Blend', 48.84, 15);
insert into dish (name, description, cost, business_id_business) values ('Tabasco Sauce, 2 Oz', 'Tomatoes - Cherry, Yellow', 99.92, 73);
insert into dish (name, description, cost, business_id_business) values ('Myers Planters Punch', 'Cookies - Englishbay Oatmeal', 91.57, 33);
insert into dish (name, description, cost, business_id_business) values ('Apples - Spartan', 'Champagne - Brights, Dry', 79.37, 144);
insert into dish (name, description, cost, business_id_business) values ('Mushroom - Portebello', 'Lettuce - Escarole', 68.31, 18);
insert into dish (name, description, cost, business_id_business) values ('Steampan - Half Size Shallow', 'Calypso - Pineapple Passion', 73.1, 138);
insert into dish (name, description, cost, business_id_business) values ('Orange - Blood', 'Cheese - Feta', 50.84, 154);
insert into dish (name, description, cost, business_id_business) values ('Schnappes - Peach, Walkers', 'Syrup - Monin - Blue Curacao', 59.35, 183);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Ricotta', 'Praline Paste', 53.11, 21);
insert into dish (name, description, cost, business_id_business) values ('Beets - Golden', 'Beef - Top Sirloin', 23.33, 157);
insert into dish (name, description, cost, business_id_business) values ('Pepper - Gypsy Pepper', 'Cranberries - Dry', 47.68, 33);
insert into dish (name, description, cost, business_id_business) values ('Creme De Menthe Green', 'Sauce - Gravy, Au Jus, Mix', 41.12, 46);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Lasagna, Dry', 'Doilies - 12, Paper', 29.03, 126);
insert into dish (name, description, cost, business_id_business) values ('Chicken - Whole Roasting', 'Cranberries - Fresh', 53.18, 186);
insert into dish (name, description, cost, business_id_business) values ('Pastry - French Mini Assorted', 'Sole - Iqf', 45.6, 79);
insert into dish (name, description, cost, business_id_business) values ('Pork - Ground', 'Wine - Chianti Classico Riserva', 11.16, 145);
insert into dish (name, description, cost, business_id_business) values ('General Purpose Trigger', 'Beef - Short Ribs', 97.98, 5);
insert into dish (name, description, cost, business_id_business) values ('Coffee Cup 12oz 5342cd', 'Pepper - Pablano', 32.32, 54);
insert into dish (name, description, cost, business_id_business) values ('Bread Crumbs - Panko', 'Flavouring - Orange', 21.96, 195);
insert into dish (name, description, cost, business_id_business) values ('Pepper - Yellow Bell', 'Flavouring - Raspberry', 8.35, 176);
insert into dish (name, description, cost, business_id_business) values ('Cinnamon - Stick', 'Soup Campbells - Tomato Bisque', 66.75, 63);
insert into dish (name, description, cost, business_id_business) values ('Five Alive Citrus', 'Vinegar - Tarragon', 84.08, 58);
insert into dish (name, description, cost, business_id_business) values ('Bay Leaf Fresh', 'Eggplant - Regular', 33.69, 170);
insert into dish (name, description, cost, business_id_business) values ('Stock - Chicken, White', 'Beans - Green', 51.5, 18);
insert into dish (name, description, cost, business_id_business) values ('Clam Nectar', 'Wine - Chateau Aqueria Tavel', 13.33, 122);
insert into dish (name, description, cost, business_id_business) values ('Cod - Fillets', 'Truffle Shells - White Chocolate', 75.01, 5);
insert into dish (name, description, cost, business_id_business) values ('Pork Loin Bine - In Frenched', 'Browning Caramel Glace', 68.68, 101);
insert into dish (name, description, cost, business_id_business) values ('Mushroom - Chantrelle, Fresh', 'Trueblue - Blueberry', 6.67, 22);
insert into dish (name, description, cost, business_id_business) values ('Carrots - Mini, Stem On', 'Veal - Leg, Provimi - 50 Lb Max', 10.73, 52);
insert into dish (name, description, cost, business_id_business) values ('Wine - Red, Pelee Island Merlot', 'Appetizer - Shrimp Puff', 91.96, 178);
insert into dish (name, description, cost, business_id_business) values ('Oneshot Automatic Soap System', 'Onions - Green', 14.98, 118);
insert into dish (name, description, cost, business_id_business) values ('Mushroom - Lg - Cello', 'Wine - Red, Antinori Santa', 79.61, 168);
insert into dish (name, description, cost, business_id_business) values ('Steampan - Half Size Shallow', 'Lemonade - Black Cherry, 591 Ml', 88.18, 161);
insert into dish (name, description, cost, business_id_business) values ('Cake - Mini Potato Pancake', 'Cheese - Cheddar With Claret', 9.9, 105);
insert into dish (name, description, cost, business_id_business) values ('Truffle Shells - White Chocolate', 'Alize Sunset', 39.72, 31);
insert into dish (name, description, cost, business_id_business) values ('Sauce - Plum', 'Lamb Rack - Ontario', 29.15, 152);
insert into dish (name, description, cost, business_id_business) values ('Saskatoon Berries - Frozen', 'Quail - Whole, Bone - In', 22.11, 5);
insert into dish (name, description, cost, business_id_business) values ('Juice - Cranberry 284ml', 'Paste - Black Olive', 53.59, 142);
insert into dish (name, description, cost, business_id_business) values ('Beef - Tongue, Cooked', 'Plums - Red', 58.27, 40);
insert into dish (name, description, cost, business_id_business) values ('Sugar - Splenda Sweetener', 'Veal - Leg, Provimi - 50 Lb Max', 85.87, 99);
insert into dish (name, description, cost, business_id_business) values ('Wine - Rubyport', 'Mustard Prepared', 76.27, 80);
insert into dish (name, description, cost, business_id_business) values ('Bananas', 'Tuna - Yellowfin', 6.55, 55);
insert into dish (name, description, cost, business_id_business) values ('Veal - Leg', 'Wine - Trimbach Pinot Blanc', 41.25, 142);
insert into dish (name, description, cost, business_id_business) values ('Napkin Colour', 'Veal - Chops, Split, Frenched', 14.67, 4);
insert into dish (name, description, cost, business_id_business) values ('Sansho Powder', 'Sauce - Bernaise, Mix', 80.4, 110);
insert into dish (name, description, cost, business_id_business) values ('Cake Slab', 'Wine - White, Riesling, Henry Of', 58.69, 140);
insert into dish (name, description, cost, business_id_business) values ('Mix - Cocktail Ice Cream', 'Wine - White Cab Sauv.on', 14.15, 49);
insert into dish (name, description, cost, business_id_business) values ('Muffin Hinge Container 6', 'Sauce - Oyster', 56.02, 50);
insert into dish (name, description, cost, business_id_business) values ('The Pop Shoppe Pinapple', 'Veal - Brisket, Provimi,bnls', 20.79, 119);
insert into dish (name, description, cost, business_id_business) values ('Wine - Tribal Sauvignon', 'Table Cloth 72x144 White', 99.97, 42);
insert into dish (name, description, cost, business_id_business) values ('Olives - Black, Pitted', 'Glass Clear 7 Oz Xl', 83.73, 79);
insert into dish (name, description, cost, business_id_business) values ('Tabasco Sauce, 2 Oz', 'Tea - Herbal Orange Spice', 89.77, 159);
insert into dish (name, description, cost, business_id_business) values ('Apple - Granny Smith', 'Pie Pecan', 38.95, 121);
insert into dish (name, description, cost, business_id_business) values ('Bouillion - Fish', 'Peach - Halves', 50.74, 163);
insert into dish (name, description, cost, business_id_business) values ('Sesame Seed', 'Chocolate - Pistoles, Lactee, Milk', 71.94, 138);
insert into dish (name, description, cost, business_id_business) values ('Eggwhite Frozen', 'Yogurt - Banana, 175 Gr', 63.13, 182);
insert into dish (name, description, cost, business_id_business) values ('Doilies - 10, Paper', 'Pants Custom Dry Clean', 61.98, 182);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Iceberg', 'Beef - Ox Tongue, Pickled', 38.37, 86);
insert into dish (name, description, cost, business_id_business) values ('Pepsi - 600ml', 'Water - San Pellegrino', 73.64, 132);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Penne Primavera, Single', 'Wine - Cotes Du Rhone', 15.79, 42);
insert into dish (name, description, cost, business_id_business) values ('Oneshot Automatic Soap System', 'Bamboo Shoots - Sliced', 71.53, 53);
insert into dish (name, description, cost, business_id_business) values ('Alize Gold Passion', 'Beans - Kidney White', 39.2, 146);
insert into dish (name, description, cost, business_id_business) values ('Bread - Bistro White', 'Dried Figs', 91.37, 25);
insert into dish (name, description, cost, business_id_business) values ('Kellogs Special K Cereal', 'Calypso - Black Cherry Lemonade', 90.33, 129);
insert into dish (name, description, cost, business_id_business) values ('White Baguette', 'Cheese - Sheep Milk', 38.95, 192);
insert into dish (name, description, cost, business_id_business) values ('Sugar Thermometer', 'Trout - Rainbow, Fresh', 50.36, 124);
insert into dish (name, description, cost, business_id_business) values ('Nescafe - Frothy French Vanilla', 'Wine - Pinot Noir Pond Haddock', 64.32, 118);
insert into dish (name, description, cost, business_id_business) values ('Cabbage - Red', 'Butter - Salted, Micro', 35.57, 8);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Ricotta', 'Island Oasis - Lemonade', 69.51, 105);
insert into dish (name, description, cost, business_id_business) values ('Nut - Pecan, Pieces', 'Wine - Red, Metus Rose', 44.86, 144);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Cheddar, Mild', 'Veal - Sweetbread', 62.04, 28);
insert into dish (name, description, cost, business_id_business) values ('Apricots - Halves', 'Wine - Two Oceans Cabernet', 53.61, 1);
insert into dish (name, description, cost, business_id_business) values ('Oil - Macadamia', 'Quail - Whole, Bone - In', 15.9, 104);
insert into dish (name, description, cost, business_id_business) values ('Cornstarch', 'Jam - Apricot', 59.1, 5);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chardonnay Mondavi', 'Olives - Morracan Dired', 79.74, 68);
insert into dish (name, description, cost, business_id_business) values ('Longos - Grilled Chicken With', 'Chinese Foods - Pepper Beef', 75.72, 63);
insert into dish (name, description, cost, business_id_business) values ('Wine - Zinfandel Rosenblum', 'Tomatoes - Heirloom', 64.11, 176);
insert into dish (name, description, cost, business_id_business) values ('Asparagus - Green, Fresh', 'Wine - Alsace Gewurztraminer', 19.87, 90);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Perron Cheddar', 'Potato - Sweet', 64.1, 126);
insert into dish (name, description, cost, business_id_business) values ('Venison - Ground', 'Phyllo Dough', 80.24, 108);
insert into dish (name, description, cost, business_id_business) values ('Brandy Cherry - Mcguinness', 'Sauce - Vodka Blush', 65.11, 88);
insert into dish (name, description, cost, business_id_business) values ('Veal - Ground', 'Oil - Grapeseed Oil', 54.53, 191);
insert into dish (name, description, cost, business_id_business) values ('Bagel - Sesame Seed Presliced', 'Juice - Cranberry 284ml', 22.13, 72);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Linguini, Dry', 'Cheese - Roquefort Pappillon', 18.34, 76);
insert into dish (name, description, cost, business_id_business) values ('Soup Campbells Beef With Veg', 'Pizza Pizza Dough', 41.66, 89);
insert into dish (name, description, cost, business_id_business) values ('Cognac - Courvaisier', 'Rice Wine - Aji Mirin', 36.96, 91);
insert into dish (name, description, cost, business_id_business) values ('Salt - Kosher', 'Wine - Segura Viudas Aria Brut', 46.06, 78);
insert into dish (name, description, cost, business_id_business) values ('Puff Pastry - Sheets', 'Nut - Pumpkin Seeds', 88.21, 198);
insert into dish (name, description, cost, business_id_business) values ('Yams', 'Pastry - Apple Large', 18.28, 102);
insert into dish (name, description, cost, business_id_business) values ('Ham - Virginia', 'Wine - Pinot Grigio Collavini', 13.81, 1);
insert into dish (name, description, cost, business_id_business) values ('Swordfish Loin Portions', 'Flower - Leather Leaf Fern', 40.23, 142);
insert into dish (name, description, cost, business_id_business) values ('Appetizer - Mini Egg Roll, Shrimp', 'Milk 2% 500 Ml', 37.37, 155);
insert into dish (name, description, cost, business_id_business) values ('Everfresh Products', 'Capers - Ox Eye Daisy', 64.63, 33);
insert into dish (name, description, cost, business_id_business) values ('Taro Leaves', 'Rootbeer', 46.86, 185);
insert into dish (name, description, cost, business_id_business) values ('Veal - Loin', 'Capers - Pickled', 29.2, 179);
insert into dish (name, description, cost, business_id_business) values ('Coke - Diet, 355 Ml', 'Pastry - Trippleberry Muffin - Mini', 83.26, 43);
insert into dish (name, description, cost, business_id_business) values ('Apple - Macintosh', 'Pears - Bartlett', 55.84, 41);
insert into dish (name, description, cost, business_id_business) values ('Salmon - Atlantic, Skin On', 'Cheese - Brick With Onion', 71.13, 33);
insert into dish (name, description, cost, business_id_business) values ('Beef Cheek Fresh', 'Cleaner - Lime Away', 55.62, 66);
insert into dish (name, description, cost, business_id_business) values ('Lamb - Leg, Boneless', 'Longos - Lasagna Beef', 39.07, 27);
insert into dish (name, description, cost, business_id_business) values ('Chivas Regal - 12 Year Old', 'Piping - Bags Quizna', 48.0, 58);
insert into dish (name, description, cost, business_id_business) values ('Veal - Round, Eye Of', 'Flour - Bread', 97.26, 145);
insert into dish (name, description, cost, business_id_business) values ('Yokaline', 'Table Cloth 120 Round White', 32.78, 120);
insert into dish (name, description, cost, business_id_business) values ('Dc - Sakura Fu', 'Pasta - Lasagna, Dry', 83.57, 112);
insert into dish (name, description, cost, business_id_business) values ('Apple - Granny Smith', 'Vinegar - White', 61.95, 37);
insert into dish (name, description, cost, business_id_business) values ('Cookies - Englishbay Oatmeal', 'Cookies - Englishbay Oatmeal', 29.72, 54);
insert into dish (name, description, cost, business_id_business) values ('Mussels - Frozen', 'Bread Roll Foccacia', 91.79, 168);
insert into dish (name, description, cost, business_id_business) values ('Cheese Cloth No 60', 'Tomatoes - Grape', 16.24, 75);
insert into dish (name, description, cost, business_id_business) values ('Red Pepper Paste', 'Pate - Peppercorn', 60.59, 121);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells Mushroom', 'Wine - Sicilia Igt Nero Avola', 50.18, 128);
insert into dish (name, description, cost, business_id_business) values ('Venison - Striploin', 'Beef - Ox Tail, Frozen', 95.55, 109);
insert into dish (name, description, cost, business_id_business) values ('Bread - Bagels, Mini', 'Beef Striploin Aaa', 36.2, 46);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Oka', 'Swiss Chard - Red', 83.86, 112);
insert into dish (name, description, cost, business_id_business) values ('Yogurt - Cherry, 175 Gr', 'Bowl 12 Oz - Showcase 92012', 59.13, 176);
insert into dish (name, description, cost, business_id_business) values ('Cup Translucent 9 Oz', 'Lemonade - Island Tea, 591 Ml', 41.64, 18);
insert into dish (name, description, cost, business_id_business) values ('Miso Paste White', 'Cornstarch', 18.83, 23);
insert into dish (name, description, cost, business_id_business) values ('Sea Urchin', 'Nut - Walnut, Chopped', 29.61, 88);
insert into dish (name, description, cost, business_id_business) values ('Squash - Pattypan, Yellow', 'Chevril', 39.91, 128);
insert into dish (name, description, cost, business_id_business) values ('Dc Hikiage Hira Huba', 'Food Colouring - Orange', 89.88, 51);
insert into dish (name, description, cost, business_id_business) values ('Thyme - Fresh', 'Pepper - Red Bell', 71.18, 52);
insert into dish (name, description, cost, business_id_business) values ('Flour - Bran, Red', 'Pasta - Canelloni', 90.64, 193);
insert into dish (name, description, cost, business_id_business) values ('Wine - Barbera Alba Doc 2001', 'Jam - Marmalade, Orange', 48.04, 94);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chardonnay Mondavi', 'Oil - Food, Lacquer Spray', 59.14, 2);
insert into dish (name, description, cost, business_id_business) values ('Kellogs All Bran Bars', 'Sauce - Rosee', 41.99, 140);
insert into dish (name, description, cost, business_id_business) values ('Mop Head - Cotton, 24 Oz', 'Mushroom - Shitake, Fresh', 67.87, 159);
insert into dish (name, description, cost, business_id_business) values ('Cleaner - Comet', 'Squash - Acorn', 95.71, 177);
insert into dish (name, description, cost, business_id_business) values ('Wine - Delicato Merlot', 'Eggplant Oriental', 72.63, 161);
insert into dish (name, description, cost, business_id_business) values ('Cauliflower', 'Nut - Almond, Blanched, Sliced', 17.08, 57);
insert into dish (name, description, cost, business_id_business) values ('Cocktail Napkin Blue', 'Tomato - Tricolor Cherry', 14.59, 121);
insert into dish (name, description, cost, business_id_business) values ('Water - Perrier', 'Mace', 17.68, 113);
insert into dish (name, description, cost, business_id_business) values ('Foil Wrap', 'Ginger - Crystalized', 69.82, 69);
insert into dish (name, description, cost, business_id_business) values ('Slt - Individual Portions', 'Kirsch - Schloss', 38.53, 159);
insert into dish (name, description, cost, business_id_business) values ('Loquat', 'Salsify, Organic', 76.03, 30);
insert into dish (name, description, cost, business_id_business) values ('Nut - Macadamia', 'Seaweed Green Sheets', 15.38, 182);
insert into dish (name, description, cost, business_id_business) values ('Versatainer Nc - 9388', 'Turkey - Breast, Smoked', 64.93, 179);
insert into dish (name, description, cost, business_id_business) values ('Pectin', 'Wine - Sicilia Igt Nero Avola', 27.14, 53);
insert into dish (name, description, cost, business_id_business) values ('Truffle Cups - Red', 'Veal - Insides, Grains', 26.89, 68);
insert into dish (name, description, cost, business_id_business) values ('Rice - Brown', 'Wine - Red, Lurton Merlot De', 80.59, 92);
insert into dish (name, description, cost, business_id_business) values ('Yoghurt Tubes', 'Beer - Sleemans Cream Ale', 13.75, 19);
insert into dish (name, description, cost, business_id_business) values ('Lychee', 'Appetizer - Southwestern', 74.34, 191);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chateauneuf Du Pape', 'Nori Sea Weed - Gold Label', 79.47, 48);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Iceberg', 'Bread - Pain Au Liat X12', 38.13, 181);
insert into dish (name, description, cost, business_id_business) values ('Cattail Hearts', 'Carbonated Water - Orange', 98.32, 141);
insert into dish (name, description, cost, business_id_business) values ('Bread Bowl Plain', 'Carbonated Water - Blackberry', 47.26, 97);
insert into dish (name, description, cost, business_id_business) values ('Sprouts - Baby Pea Tendrils', 'Shrimp - 16 - 20 Cooked, Peeled', 7.5, 179);
insert into dish (name, description, cost, business_id_business) values ('Soup - Tomato Mush. Florentine', 'Bread - Multigrain', 30.35, 46);
insert into dish (name, description, cost, business_id_business) values ('Hot Choc Vending', 'Capers - Pickled', 94.72, 171);
insert into dish (name, description, cost, business_id_business) values ('Crab - Dungeness, Whole, live', 'Wine - Chianti Classica Docg', 39.23, 150);
insert into dish (name, description, cost, business_id_business) values ('Sloe Gin - Mcguinness', 'Yeast - Fresh, Fleischman', 59.51, 179);
insert into dish (name, description, cost, business_id_business) values ('Lemon Balm - Fresh', 'Apple - Granny Smith', 12.98, 82);
insert into dish (name, description, cost, business_id_business) values ('Compound - Rum', 'Icecream - Dstk Strw Chseck', 6.02, 130);
insert into dish (name, description, cost, business_id_business) values ('Cherries - Fresh', 'Brandy Apricot', 49.4, 136);
insert into dish (name, description, cost, business_id_business) values ('Tea - English Breakfast', 'Chinese Foods - Chicken', 13.29, 42);
insert into dish (name, description, cost, business_id_business) values ('Langers - Ruby Red Grapfruit', 'Bouillion - Fish', 87.98, 189);
insert into dish (name, description, cost, business_id_business) values ('Wine - Hardys Bankside Shiraz', 'Yucca', 23.02, 159);
insert into dish (name, description, cost, business_id_business) values ('Lobster - Canned Premium', 'Pork - Back, Long Cut, Boneless', 82.46, 149);
insert into dish (name, description, cost, business_id_business) values ('Tomato Paste', 'Pasta - Penne Primavera, Single', 10.9, 105);
insert into dish (name, description, cost, business_id_business) values ('Chocolate Liqueur - Godet White', 'Goulash Seasoning', 92.47, 129);
insert into dish (name, description, cost, business_id_business) values ('Soup - Campbells, Creamy', 'Veal - Eye Of Round', 69.13, 8);
insert into dish (name, description, cost, business_id_business) values ('Flower - Daisies', 'Pears - Bosc', 77.05, 3);
insert into dish (name, description, cost, business_id_business) values ('Flounder - Fresh', 'Rosemary - Primerba, Paste', 68.09, 100);
insert into dish (name, description, cost, business_id_business) values ('Lid Coffee Cup 8oz Blk', 'Cake - Mini Potato Pancake', 54.96, 183);
insert into dish (name, description, cost, business_id_business) values ('Chicken - Thigh, Bone In', 'Silicone Paper 16.5x24', 38.04, 32);
insert into dish (name, description, cost, business_id_business) values ('Mousse - Passion Fruit', 'Tumeric', 78.46, 195);
insert into dish (name, description, cost, business_id_business) values ('Mikes Hard Lemonade', 'Turkey Leg With Drum And Thigh', 8.14, 39);
insert into dish (name, description, cost, business_id_business) values ('Bread - White Mini Epi', 'Wine - Sicilia Igt Nero Avola', 86.26, 150);
insert into dish (name, description, cost, business_id_business) values ('Wine - Red, Pinot Noir, Chateau', 'Sobe - Lizard Fuel', 30.65, 73);
insert into dish (name, description, cost, business_id_business) values ('Flour - Whole Wheat', 'Longos - Chicken Caeser Salad', 10.3, 181);
insert into dish (name, description, cost, business_id_business) values ('Chocolate - Dark', 'Tart - Butter Plain Squares', 78.68, 70);
insert into dish (name, description, cost, business_id_business) values ('Corn - On The Cob', 'Fond - Chocolate', 81.66, 13);
insert into dish (name, description, cost, business_id_business) values ('Beef - Tenderloin - Aa', 'Langers - Ruby Red Grapfruit', 14.96, 85);
insert into dish (name, description, cost, business_id_business) values ('Soap - Pine Sol Floor Cleaner', 'Bacardi Breezer - Tropical', 38.16, 184);
insert into dish (name, description, cost, business_id_business) values ('Numi - Assorted Teas', 'Milk - Buttermilk', 48.32, 32);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Taleggio D.o.p.', 'Veal - Leg', 71.35, 140);
insert into dish (name, description, cost, business_id_business) values ('Juice - Propel Sport', 'Foil - 4oz Custard Cup', 90.7, 25);
insert into dish (name, description, cost, business_id_business) values ('Soup - Knorr, French Onion', 'Lamb - Sausage Casings', 59.64, 87);
insert into dish (name, description, cost, business_id_business) values ('Muffin - Mix - Mango Sour Cherry', 'Tart Shells - Savory, 3', 71.2, 168);
insert into dish (name, description, cost, business_id_business) values ('Wine - Jackson Triggs Okonagan', 'Truffle Shells - Semi - Sweet', 60.54, 149);
insert into dish (name, description, cost, business_id_business) values ('Rootbeer', 'Wine - German Riesling', 44.66, 107);
insert into dish (name, description, cost, business_id_business) values ('Vol Au Vents', 'Rice Paper', 83.6, 66);
insert into dish (name, description, cost, business_id_business) values ('Phyllo Dough', 'Wine - Trimbach Pinot Blanc', 93.46, 48);
insert into dish (name, description, cost, business_id_business) values ('Remy Red', 'Juice - Happy Planet', 79.32, 131);
insert into dish (name, description, cost, business_id_business) values ('Tomatoes - Grape', 'Shiro Miso', 45.56, 56);
insert into dish (name, description, cost, business_id_business) values ('Extract Vanilla Pure', 'Soup - Knorr, Chicken Gumbo', 39.84, 101);
insert into dish (name, description, cost, business_id_business) values ('Orange Roughy 4/6 Oz', 'Bread - Sour Batard', 20.98, 18);
insert into dish (name, description, cost, business_id_business) values ('Ham - Procutinni', 'Lamb Leg - Bone - In Nz', 43.85, 31);
insert into dish (name, description, cost, business_id_business) values ('Veal - Inside Round / Top, Lean', 'Chicken - Leg / Back Attach', 82.33, 121);
insert into dish (name, description, cost, business_id_business) values ('Sugar - Individual Portions', 'Coffee Swiss Choc Almond', 44.73, 166);
insert into dish (name, description, cost, business_id_business) values ('Apple - Macintosh', 'Wine - Rubyport', 97.84, 169);
insert into dish (name, description, cost, business_id_business) values ('Lemon Pepper', 'Mushroom - White Button', 62.44, 152);
insert into dish (name, description, cost, business_id_business) values ('Cookies Cereal Nut', 'Mace', 93.86, 161);
insert into dish (name, description, cost, business_id_business) values ('Mousse - Mango', 'Dried Peach', 56.2, 23);
insert into dish (name, description, cost, business_id_business) values ('Lettuce - Boston Bib', 'Energy Drink - Franks Original', 48.16, 188);
insert into dish (name, description, cost, business_id_business) values ('Sage - Ground', 'Oil - Pumpkinseed', 36.59, 8);
insert into dish (name, description, cost, business_id_business) values ('Food Colouring - Green', 'Beef - Inside Round', 70.4, 51);
insert into dish (name, description, cost, business_id_business) values ('Lady Fingers', 'Broom Handle', 33.88, 153);
insert into dish (name, description, cost, business_id_business) values ('Tomatoes - Grape', 'Dome Lid Clear P92008h', 28.35, 121);
insert into dish (name, description, cost, business_id_business) values ('Filling - Mince Meat', 'Mussels - Frozen', 38.69, 65);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chateauneuf Du Pape', 'Salt - Celery', 18.3, 26);
insert into dish (name, description, cost, business_id_business) values ('Veal - Kidney', 'Greens Mustard', 84.38, 180);
insert into dish (name, description, cost, business_id_business) values ('Plaintain', 'Wooden Mop Handle', 38.32, 26);
insert into dish (name, description, cost, business_id_business) values ('Pastry - Carrot Muffin - Mini', 'Dish Towel', 30.71, 142);
insert into dish (name, description, cost, business_id_business) values ('Cheese - Brie, Cups 125g', 'Oil - Macadamia', 26.95, 75);
insert into dish (name, description, cost, business_id_business) values ('Chinese Foods - Pepper Beef', 'Oil - Grapeseed Oil', 27.2, 33);
insert into dish (name, description, cost, business_id_business) values ('Anchovy In Oil', 'Appetizer - Shrimp Puff', 23.97, 47);
insert into dish (name, description, cost, business_id_business) values ('The Pop Shoppe - Cream Soda', 'Chutney Sauce', 27.29, 175);
insert into dish (name, description, cost, business_id_business) values ('Spaghetti Squash', 'Chutney Sauce - Mango', 52.09, 128);
insert into dish (name, description, cost, business_id_business) values ('Rice Pilaf, Dry,package', 'Cocoa Powder - Dutched', 72.21, 44);
insert into dish (name, description, cost, business_id_business) values ('Crab - Meat', 'Bagel - Everything', 24.28, 30);
insert into dish (name, description, cost, business_id_business) values ('Arctic Char - Fresh, Whole', 'Ice Cream Bar - Hagen Daz', 12.18, 88);
insert into dish (name, description, cost, business_id_business) values ('Beef Dry Aged Tenderloin Aaa', 'Wine - White, Colubia Cresh', 59.42, 120);
insert into dish (name, description, cost, business_id_business) values ('Scallops - 10/20', 'Blueberries', 88.98, 200);
insert into dish (name, description, cost, business_id_business) values ('Ocean Spray - Ruby Red', 'Wine - Trimbach Pinot Blanc', 83.25, 200);
insert into dish (name, description, cost, business_id_business) values ('Venison - Striploin', 'Shrimp - Black Tiger 6 - 8', 56.85, 46);
insert into dish (name, description, cost, business_id_business) values ('Tarragon - Primerba, Paste', 'Wine - White, Ej Gallo', 67.52, 2);
insert into dish (name, description, cost, business_id_business) values ('Red Snapper - Fillet, Skin On', 'Chinese Lemon Pork', 64.01, 26);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Gnocchi, Potato', 'Tea - Orange Pekoe', 62.6, 152);
insert into dish (name, description, cost, business_id_business) values ('Puff Pastry - Sheets', 'Liquid Aminios Acid - Braggs', 10.43, 58);
insert into dish (name, description, cost, business_id_business) values ('Caviar - Salmon', 'French Pastries', 42.75, 88);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Fusili, Dry', 'Jerusalem Artichoke', 29.06, 182);
insert into dish (name, description, cost, business_id_business) values ('Beer - Paulaner Hefeweisse', 'Chicken - Breast, 5 - 7 Oz', 28.37, 57);
insert into dish (name, description, cost, business_id_business) values ('Pineapple - Canned, Rings', 'Cookie Trail Mix', 10.21, 95);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Cappellini, Dry', 'Wine - Prosecco Valdobienne', 76.81, 38);
insert into dish (name, description, cost, business_id_business) values ('Bread - Dark Rye, Loaf', 'Oil - Canola', 23.93, 110);
insert into dish (name, description, cost, business_id_business) values ('Table Cloth 144x90 White', 'Cheese - Brie', 49.59, 50);
insert into dish (name, description, cost, business_id_business) values ('Dried Figs', 'Catfish - Fillets', 74.28, 89);
insert into dish (name, description, cost, business_id_business) values ('Cranberries - Dry', 'Crab - Imitation Flakes', 50.12, 109);
insert into dish (name, description, cost, business_id_business) values ('Wine - Chardonnay South', 'Wine - Vouvray Cuvee Domaine', 89.44, 45);
insert into dish (name, description, cost, business_id_business) values ('Zucchini - Mini, Green', 'Barley - Pearl', 47.15, 94);
insert into dish (name, description, cost, business_id_business) values ('Tart - Lemon', 'Tart Shells - Sweet, 4', 45.33, 22);
insert into dish (name, description, cost, business_id_business) values ('Jam - Raspberry,jar', 'Gherkin - Sour', 10.55, 73);
insert into dish (name, description, cost, business_id_business) values ('Sea Urchin', 'Veal - Kidney', 43.32, 79);
insert into dish (name, description, cost, business_id_business) values ('Truffle - Peelings', 'Pasta - Tortellini, Fresh', 56.04, 134);
insert into dish (name, description, cost, business_id_business) values ('Juice - Lime', 'Croissants Thaw And Serve', 55.92, 153);
insert into dish (name, description, cost, business_id_business) values ('Ecolab - Hobart Washarm End Cap', 'Sun - Dried Tomatoes', 31.12, 95);
insert into dish (name, description, cost, business_id_business) values ('Island Oasis - Strawberry', 'Chicken Breast Wing On', 79.85, 3);
insert into dish (name, description, cost, business_id_business) values ('Wine - Domaine Boyar Royal', 'Sauce - Balsamic Viniagrette', 60.82, 152);
insert into dish (name, description, cost, business_id_business) values ('Apples - Sliced / Wedge', 'Juice - Grapefruit, 341 Ml', 19.15, 125);
insert into dish (name, description, cost, business_id_business) values ('Pasta - Tortellini, Fresh', 'Corn - Cream, Canned', 84.4, 196);
insert into dish (name, description, cost, business_id_business) values ('Chinese Foods - Thick Noodles', 'Pork - Ham Hocks - Smoked', 65.52, 99);
insert into dish (name, description, cost, business_id_business) values ('Nut - Cashews, Whole, Raw', 'Glove - Cutting', 40.39, 130);
insert into dish (name, description, cost, business_id_business) values ('Chocolate Bar - Oh Henry', 'Wine - Chianti Classica Docg', 27.1, 75);
insert into dish (name, description, cost, business_id_business) values ('Yogurt - Blueberry, 175 Gr', 'Buttons', 51.31, 115);
insert into dish (name, description, cost, business_id_business) values ('Cheese - St. Paulin', 'Lettuce - Lambs Mash', 67.41, 98);
insert into dish (name, description, cost, business_id_business) values ('Basil - Thai', 'Syrup - Monin - Blue Curacao', 23.64, 55);
insert into dish (name, description, cost, business_id_business) values ('Drambuie', 'Dawn Professionl Pot And Pan', 46.73, 83);
insert into dish (name, description, cost, business_id_business) values ('Almonds Ground Blanched', 'Sherbet - Raspberry', 19.03, 155);
insert into dish (name, description, cost, business_id_business) values ('Dried Apple', 'Shortbread - Cookie Crumbs', 91.21, 49);
insert into dish (name, description, cost, business_id_business) values ('Silicone Paper 16.5x24', 'Cake - Cheese Cake 9 Inch', 37.58, 57);
